export const regions = [
  'Australia and New Zealand',
  'Central Asia',
  'Eastern Asia',
  'Eastern Europe',
  'Latin America and the Caribbean',
  'Melanesia',
  'Micronesia',
  'Northern Africa',
  'Northern America',
  'Northern Europe',
  'Polynesia',
  'South-eastern Asia',
  'Southern Asia',
  'Southern Europe',
  'Sub-Saharan Africa',
  'Western Asia',
  'Western Europe',
]
