export const units = [
  'square meter',
  'square kilometer',
  'Count per sq km',
  'Count per m',
  'people per square km',
  'people per sqare m',
  'Population',
  'Percent',
  'Categories',
  'Unitless (index)',
  'meter',
  'kilometer',
  'Rate per 100,000 population',
  'litre',
  'US Dollars',
  'Hectare',
  'Count',
  'people per pixel',
]
