name: "New Feature Request"
description: "Suggest an idea for this project"
title: "[FEATURE] "
labels: [enhancement]

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this feature request! Before filling this feature request, please make sure that:
        - You have the latest version of the project. especially the `develop` branch.
        - You have searched the [issues](https://github.com/UNDP-Data/geohub/issues) for similar feature requests.

  - type: textarea
    id: feature-description
    attributes:
      label: "Feature Description"
      description: "A clear and concise description of what the feature is."
    validations:
      required: true

  - type: textarea
    id: feature-implementation
    attributes:
      label: "Feature Implementation"
      description: "A clear and concise description of how the feature should be implemented."
    validations:
      required: false

  - type: textarea
    id: feature-alternatives
    attributes:
      label: "Feature Alternatives"
      description: "A clear and concise description of any alternative solutions or features you've considered."
    validations:
      required: false

  - type: textarea
    id: feature-impact
    attributes:
      label: "Feature Impact"
      description: "A clear and concise description of the impact of the feature."
    validations:
      required: false

  - type: textarea
    id: feature-rationale
    attributes:
      label: "Feature Rationale"
      description: "A clear and concise description of why you think the feature is good."
    validations:
      required: false

  - type: textarea
    id: feature-considerations
    attributes:
      label: "Feature Considerations"
      description: "A clear and concise description of any considerations for the feature."
    validations:
      required: false

  - type: textarea
    id: feature-requirements
    attributes:
      label: "Feature Requirements"
      description: "A clear and concise description of any requirements for the feature."
    validations:
      required: false