apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: test-cert
  namespace: default
spec:
  secretName: test-cert-tls
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  commonName: "titiler-dev.undpgeohub.org"
  dnsNames:
    - "titiler-dev.undpgeohub.org"
