version: "3"

services:
  geohub:
    image: undp-data/geohub:latest
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
    restart: unless-stopped
    container_name: geohub
    ports:
      - "5173:5173"
    environment:
      # editable in .env
      - MARTIN_API_ENDPOINT=${MARTIN_API_ENDPOINT:-''}
      - PGTILESERV_API_ENDPOINT=${PGTILESERV_API_ENDPOINT:-''}
      - TITILER_ENDPOINT=${TITILER_ENDPOINT:-''}
      - AZURE_STORAGE_ACCOUNT=${AZURE_STORAGE_ACCOUNT:-''}
      - AZURE_STORAGE_ACCOUNT_UPLOAD=${AZURE_STORAGE_ACCOUNT_UPLOAD:-''}
      - AZURE_STORAGE_ACCESS_KEY_UPLOAD=${AZURE_STORAGE_ACCESS_KEY_UPLOAD:-''}
      - AZURE_SERVICE_BUS_CONNECTIONSTRING=${AZURE_SERVICE_BUS_CONNECTIONSTRING:-''}
      - AZURE_SERVICE_BUS_QUEUE_NAME=${AZURE_SERVICE_BUS_QUEUE_NAME:-''}
      - DATABASE_CONNECTION=${DATABASE_CONNECTION:-''}
      - AUTH_SECRET=${AUTH_SECRET:-''}
      - AZURE_AD_TENANT_ID=${AZURE_AD_TENANT_ID:-''}
      - AZURE_AD_CLIENT_ID=${AZURE_AD_CLIENT_ID:-''}
      - AZURE_AD_CLIENT_SECRET=${AZURE_AD_CLIENT_SECRET:-''}
      - GEOHUB_GITHUB_ID=${GEOHUB_GITHUB_ID:-''}
      - GEOHUB_GITHUB_SECRET=${GEOHUB_GITHUB_SECRET:-''}
      - AZURE_PUBSUB_CONNECTIONSTRING=${AZURE_PUBSUB_CONNECTIONSTRING:-''}
      - AZURE_PUBSUB_GROUP_DATA_PIPELINE=${AZURE_PUBSUB_GROUP_DATA_PIPELINE:-'datapipeline'}
      - GEOHUB_STATIC_IMAGE_API=${GEOHUB_STATIC_IMAGE_API:-'https://staticimage.undpgeohub.org/api'}
      - GEOHUB_API_ENDPOINT=${GEOHUB_API_ENDPOINT:-'https://dev.undpgeohub.org'}
    volumes:
      - ../sites/geohub:/app/sites/geohub
      - ../packages:/app/packages
    entrypoint: pnpm --filter="./sites/geohub" dev --host
