import { 
    AZURE_STORAGE_ACCOUNT, 
    AZURE_STORAGE_ACCESS_KEY, 
    DATABASE_CONNECTION 
} from '$env/static/private'

export { 
    AZURE_STORAGE_ACCOUNT, 
    AZURE_STORAGE_ACCESS_KEY,
    DATABASE_CONNECTION
}
