version: "3"

services:
  mkdocs:
    build: .
    environment:
      #Application
      - HOST=${HOST:-0.0.0.0}
      - PORT=${PORT:-8000}
      - SITE_URL=http://localhost:${PORT:-8000}
      - GITHUB_EDIT_URL=${GITHUB_EDIT_URL}
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - ./docs:/app/docs
      - ./mkdocs.yml:/app/mkdocs.yml
