site_name: GeoHub Documentation
site_description: GeoHub is UNDP's one stop shop for spatial data and analytics to support development policy makers and Connects geospatial knowledge and knowhow across the organization to enhance evidence-based decision making with relevant data-led insights. It is a repository of a wide array of data sets of the most recent time span available at your fingertips!

docs_dir: docs
site_dir: site

# Repository
repo_name: undp-data/geohub
repo_url: https://github.com/undp-data/geohub
edit_uri:
  !ENV [
    "EDIT_URL",
    "https://github.com/undp-data/geohub/blob/develop/documentation/docs",
  ]
# configuration by env https://www.mkdocs.org/user-guide/configuration/#environment-variables
site_url: !ENV ["SITE_URL", "http://localhost:8000"]

# Copyright
copyright: Copyright &copy; 2024 <a href="https://undp.org">United Nations Development Programme</a>

theme:
  name: material
  custom_dir: theme_overrides/
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: octicons/moon-24
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue grey
      accent: light blue
      toggle:
        icon: octicons/sun-24
        name: Switch to light mode
  logo: assets/images/undp-logo-blue.svg
  favicon: assets/images/favicon.svg
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    # - content.code.select
    # - content.footnote.tooltips
    # - content.tabs.link
    - content.tooltips
    # - header.autohide
    # - navigation.expand
    - navigation.footer
    - navigation.indexes
    # - navigation.instant
    # - navigation.instant.prefetch
    # - navigation.instant.progress
    # - navigation.prune
    - navigation.sections
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    # - toc.integrate

reveal:
  path: /reveal.js/dist
  transition: slide
  theme:
    name: white.css
    path: theme
  plugin:
    path: /reveal.js/plugin

extra:
  author:
    name: United Nations Development Programme
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/undp-data/geohub
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/SDGintegration
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/undp
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/UNDP
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/undp/
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/UNDP

# These extensions are chosen to be a superset of Pandoc's Markdown.
# This way, I can write in Pandoc's Markdown and have it be supported here.
# https://pandoc.org/MANUAL.html
# https://github.com/kylebarron/cogeo-mosaic/blob/mkdocs/mkdocs.yml#L50-L75
markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - codehilite:
      guess_lang: false
  - def_list
  - footnotes
  - pymdownx.arithmatex
  - pymdownx.betterem
  - pymdownx.caret:
      insert: false
  - pymdownx.details
  - pymdownx.emoji
  - pymdownx.escapeall:
      hardbreak: true
      nbsp: true
  - pymdownx.magiclink:
      hide_protocol: true
      repo_url_shortener: true
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - toc:
      permalink: true
  - pymdownx.superfences:
      # make exceptions to highlighting of code:

plugins:
  - search
  - social:
      cards_color:
        fill: "#FFFFFF"
        text: "#006eb5"
  - mkdocs-video:
      css_style:
        class: "center"
        width: "760px"
        height: "515px"
        frameborder: "0"
  # https://github.com/timvink/mkdocs-git-authors-plugin
  - git-authors
  - caption

extra_css:
  - stylesheets/extra.css

nav:
  - Home: index.md
  - Overview:
      - getting-started/overview.md
      - getting-started/importance_of_gis.md
      - Signin: getting-started/signin.md
      - getting-started/support.md
  - Data:
      - data/data_formats.md
      - data/data_store.md
      - data/data_upload.md
      - data/publish_datasets.md
      - Search Datasets:
          - data/search_datasets_table.md
          - data/search_datasets_on_map.md
          - data/search_datasets_satellite.md
      - data/best_practices.md
  - Visualization:
      - visualization/map_view.md
      - visualization/visualize_overview.md
      - Vector data visualization:
          - visualization/visualize_vector.md
          - visualization/visualize_vector_polygon.md
          - visualization/visualize_vector_3dpolygon.md
          - visualization/visualize_vector_line.md
          - visualization/visualize_vector_point.md
          - visualization/visualize_vector_heatmap.md
          - visualization/visualize_vector_circle.md
          - visualization/visualize_vector_filter.md
          - visualization/visualize_vector_label.md
      - visualization/visualize_raster.md
      - visualization/visualize_colormap.md
      - visualization/visualize_classification.md
      - visualization/handson.md
  - Analytics:
      - analytics/index.md
      - analytics/dynamic_vector.md
      - analytics/raster_base_analysis.md
      - analytics/case_studies.md
  - Sharing:
      - sharing/save_map.md
      - sharing/share_map.md
      - sharing/search_maps.md
      - sharing/export_map.md
  - Dashboards:
      - dashboards/index.md
      - dashboards/electricity.md
  - Slides:
      - slides/index.md
      - Slide operations: slides/slide_operations.md
      - Slide mode:
          - Overview:
              - getting-started/overview_slide.md
              - getting-started/importance_of_gis_slide.md
              - Signin: getting-started/signin_slide.md
              - getting-started/support_slide.md
          - Data:
              - data/data_formats_slide.md
              - data/data_store_slide.md
              - data/data_upload_slide.md
              - data/publish_datasets_slide.md
              - Search Datasets:
                  - data/search_datasets_table_slide.md
                  - data/search_datasets_on_map_slide.md
                  - data/search_datasets_satellite_slide.md
              - data/best_practices_slide.md
          - Visualization:
              - visualization/map_view_slide.md
              - visualization/visualize_overview_slide.md
              - Vector data visualization:
                  - visualization/visualize_vector_slide.md
                  - visualization/visualize_vector_polygon_slide.md
                  - visualization/visualize_vector_3dpolygon_slide.md
                  - visualization/visualize_vector_line_slide.md
                  - visualization/visualize_vector_point_slide.md
                  - visualization/visualize_vector_heatmap_slide.md
                  - visualization/visualize_vector_circle_slide.md
                  - visualization/visualize_vector_filter_slide.md
                  - visualization/visualize_vector_label_slide.md
              - visualization/visualize_raster_slide.md
              - visualization/visualize_colormap_slide.md
              - visualization/visualize_classification_slide.md
              - visualization/handson_slide.md
          - Analytics:
              - analytics/index_slide.md
              - analytics/dynamic_vector_slide.md
              - analytics/raster_base_analysis_slide.md
              - analytics/case_studies_slide.md
          - Sharing:
              - sharing/save_map_slide.md
              - sharing/share_map_slide.md
              - sharing/search_maps_slide.md
              - sharing/export_map_slide.md
          - Dashboards:
              - dashboards/index_slide.md
              - dashboards/electricity_slide.md
      - Presentations:
          - FOSS4G Prizren 2023: /assets/slides/UNDP GeoHub FOSS4G2023.pdf
          - FOSS4G UK 2023: /assets/slides/UNDP GeoHub FOSS4G UK 2023.pdf
