# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: build packages

on:
  push:
    branches:
      - main
      - develop
  pull_request:

env:
  CI: true
  PNPM_CACHE_FOLDER: .pnpm-store

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: checkout code repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: pnpm/action-setup@v2.2.4
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: pnpm

      - name: install dependencies
        run: pnpm --filter="./packages/*" install --frozen-lockfile
      - name: lint packages
        run: pnpm --filter="./packages/*" lint
      - name: format packages
        run: pnpm --filter="./packages/*" format
      - name: build packages
        run: pnpm --filter="./packages/*" build
