name: Bump geohub-data-pipeline version
on:
  # This workflow will be triggered when the new release tag is created on geohub-data-pipeline repository.concurrency:
  # https://github.com/UNDP-Data/geohub-data-pipeline/blob/main/.github/workflows/acr_docker_image.yml
  repository_dispatch:
    types: [bump-pipeline-version]
  workflow_dispatch:

jobs:
  bump-version:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: bump data-pipeline version
        run: ./backends/k8s/data-pipeline/bump-version.sh

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          branch: release/bump-geohub-data-pipeline
          title: "[RELEASE] bump version of geohub-data-pipeline"
          delete-branch: true
          commit-message: "[RELEASE] bump version of geohub-data-pipeline"
          body: |
            ## Description

            This is going to bump the version of geohub-data-pipeline to apply the new pipeline docker image to kubernetes cluster

            ---
            - Auto-generated by [create-pull-request][1]

            [1]: https://github.com/peter-evans/create-pull-request
          labels: release
          reviewers: |
            iferencik
            Thuhaa
            JinIgarashi
