name: Deploy GeoHub userguide

on:
  push:
    branches: [develop]
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v4
      - name: Install dependecies
        working-directory: ./documentation
        run: |
          pip install pipenv
          pipenv install --system

      - name: Build documentation
        working-directory: ./documentation
        run: mkdocs build

      - name: deploy userguide to Blob container
        if: ${{ (github.ref == 'refs/heads/develop') }}
        uses: bacongobbler/azure-blob-storage-upload@main
        with:
          source_dir: documentation/site
          container_name: $web
          connection_string: ${{ secrets.AZURE_STORAGE_CONNECTION_STRING_USERGUIDE }}
          # WARNING: this will overwrite existing blobs in your blob storage
          sync: "true"
