# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - undpgeohub

on:
  push:
    branches:
      - main
      - develop
  pull_request:
  workflow_dispatch:

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16]
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      # checkout code
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: actions/setup-python@v3
      - name: Install dependecies
        working-directory: ./documentation
        run: |
          pip install pipenv
          pipenv install --system

      - name: Build documentation
        working-directory: ./documentation
        run: mkdocs build

      # pnpm setup
      # refer to https://github.com/pnpm/action-setup
      - name: pnpm setup
        uses: pnpm/action-setup@v2.2.2
        with:
          version: 7
          run_install: false

      # setup Node
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - name: Get pnpm store directory
        id: pnpm-cache
        run: |
          echo "::set-output name=pnpm_cache_dir::$(pnpm store path)"
      
      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.pnpm_cache_dir }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      # install dependencies
      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      # setup environmental variables
      - name: Create environment file
        uses: SpicyPizza/create-envfile@v1.3
        with:
          envkey_AZURE_STORAGE_ACCOUNT: ${{ secrets.AZURE_STORAGE_ACCOUNT }}
          envkey_AZURE_STORAGE_ACCESS_KEY: ${{ secrets.AZURE_STORAGE_ACCESS_KEY }}
          envkey_DATABASE_CONNECTION: ${{ secrets.DATABASE_CONNECTION }}
          envkey_PUBLIC_TITILER_ENDPOINT: ${{ secrets.PUBLIC_TITILER_ENDPOINT }}
          envkey_PUBLIC_AZURE_BLOB_TOKEN: ${{ secrets.PUBLIC_AZURE_BLOB_TOKEN }}
          envkey_PUBLIC_AZURE_URL: ${{ secrets.PUBLIC_AZURE_URL }}
          envkey_PUBLIC_MARTIN_API_ENDPOINT: ${{ secrets.PUBLIC_MARTIN_API_ENDPOINT }}
          envkey_PUBLIC_PGTILESERV_API_ENDPOINT: ${{ secrets.PUBLIC_PGTILESERV_API_ENDPOINT }}   

      - name: Run lint
        run: pnpm lint

      - name: Run Prettier
        run: pnpm format

      - name: Run build
        run: pnpm build:ci

      - name: Run unit tests
        run: pnpm test

      - name: Copy package.json / lock files to build folder
        if: ${{ (github.ref == 'refs/heads/main') || (github.ref == 'refs/heads/develop') }}
        run: |
          rm -rf node_modules
          pnpm install --prod
          cp package.json build/.
          cp pnpm-lock.yaml build/.
          mv node_modules build/.

      - name: 'Deploy to Azure Web App for undpgeohub-dev'
        id: deploy-to-webapp-dev
        uses: azure/webapps-deploy@v2
        if: ${{ github.ref == 'refs/heads/develop'}}
        with:
          app-name: 'undpgeohub-dev'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_A746B2A45468422D9E5BF02A6A7ABDCE }}
          package: build

      - name: 'Deploy to Azure for undpgeohub'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        if: ${{ github.ref == 'refs/heads/main'}}
        with:
          app-name: 'undpgeohub'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_300BF55889E241EAAC5E83E800D05457 }}
          package: build
