# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - undpgeohub

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      # checkout code
      - name: Checkout code
        uses: actions/checkout@v2

      # setup Node
      - name: Install Node
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'yarn'

      # install dependencies
      - name: Create environment file
        uses: SpicyPizza/create-envfile@v1.3
        with:
          envkey_VITE_TITILER_ENDPOINT: ${{ secrets.VITE_TITILER_ENDPOINT }}
          envkey_AZURE_STORAGE_ACCOUNT: ${{ secrets.AZURE_STORAGE_ACCOUNT }}
          envkey_AZURE_STORAGE_ACCESS_KEY: ${{ secrets.AZURE_STORAGE_ACCESS_KEY }}
          envkey_VITE_BINGMAP_KEY: ${{ secrets.VITE_BINGMAP_KEY }}
          envkey_VITE_AZURE_BLOB_TOKEN: ${{ secrets.VITE_AZURE_BLOB_TOKEN }}
          envkey_VITE_AZURE_URL: ${{ secrets.VITE_AZURE_URL }}
          envkey_VITE_ADMIN_URL: ${{ secrets.VITE_ADMIN_URL }}

      # install dependencies
      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Run lint
        run: yarn ci:lint

      - name: Run Prettier
        run: yarn ci:prettier

      - name: Run build
        run: yarn ci:compile

      - name: Run unit tests
        run: yarn ci:test

      - name: Copy package.json / lock files to build folder
        if: ${{ github.ref == 'refs/heads/main' }}
        run: |
          cp package.json build/.
          cp yarn.lock build/.
          mv node_modules build/.
          mv data build/.

      - name: 'Deploy to Azure'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        if: ${{ github.ref == 'refs/heads/main'}}
        with:
          app-name: 'undpgeohub'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_300BF55889E241EAAC5E83E800D05457 }}
          package: build
