# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: CI (Static API)

on:
  push:
    paths-ignore:
      - "packages/**"
      - "sites/geohub/**"
      - "documentation/**"
    branches:
      - develop
  pull_request:
    paths-ignore:
      - "packages/**"
      - "sites/geohub/**"
      - "documentation/**"
  workflow_dispatch:

env:
  CI: true

jobs:
  build_docker:
    name: Build and deploy Docker image
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        node-version: [18]
    env:
      IMAGE_NAME: geohub-static-image-api
    environment:
      name: Static Image API
      url: https://staticimage.undpgeohub.org

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log into ACR
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.ACR_ENDPOINT }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.ACR_ENDPOINT }}/${{ env.IMAGE_NAME }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./sites/static-image-api
          push: ${{ github.ref == 'refs/heads/develop'}}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
